Spacewalk cover overlay_connection and connector with unit tests
pendulum-chain/spacewalk pull request #134
Opened 2022-11-16 20:37 UTC by cr4pt0

2022-11-17 08:07 UTC, b-yap commented on clients/stellar-relay/src/connection/connector/connector.rs
> +			receive_tx_messages: cfg.recv_tx_msgs,
nice catch!

2022-11-17 08:46 UTC, ebma requested changes
There are some nice tests, good job. 👍 
Besides my other comments, can you also fix the warnings about unused warnings etc that are shown by CI?

2022-11-17 08:46 UTC, ebma commented on clients/stellar-relay/src/connection/connector/connector.rs
> +	fn connector_get_set_hmac_keys_works() {
I would change it to `connector_get_and_set_hmac_keys_works`

2022-11-17 08:46 UTC, ebma commented on clients/stellar-relay/src/connection/connector/connector.rs
> +	}
I would move these two functions to the top of the test module so they are known to the reader of the code before being used.

2022-11-17 08:48 UTC, cr4pt0 commented
the problem is that ci shoe some wrong warning. 'create_connector' never used. But i use this function 6 times. What i can do with this one?

2022-11-17 09:11 UTC, ebma commented
Yeah I also saw that and was wondering. Maybe it's fixed by moving it more to the top, as I suggested in my comment? If it does not fix it you can ignore it.

2022-11-17 09:11 UTC, b-yap commented
@cr4pt0  maybe `#[cfg(test)]` on the function will work.

2022-11-17 09:13 UTC, ebma commented on clients/stellar-relay/src/connection/overlay_connection.rs
> +		let error_messae = "error message".to_owned();
here is a typo

2022-11-17 09:14 UTC, b-yap commented on clients/stellar-relay/src/connection/connector/connector.rs
> +
ah. try the `#[cfg(test)]` here.

2022-11-17 09:15 UTC, ebma commented
@b-yap ah true. This should be added above the declaration of the test module as it is missing right now.

2022-11-17 10:50 UTC, b-yap approved these changes
the check failure at line 87 of pallets/stellar-relay/src/libs.rs is out of scope. 

I'm approving this, based on the 2 files.

2022-11-18 14:25 UTC, ebma approved these changes

2022-11-18 14:28 UTC, merged