7 add extrinsic to initiate redeem
pendulum-chain/spacewalk pull request #15
Opened 2022-04-12 16:38 UTC by ashneverdawn

Closes #7

2022-04-13 07:46 UTC, ebma approved these changes
Looks good to me overall but I didn't test it.

2022-04-13 07:46 UTC, ebma commented on pallets/spacewalk/src/lib.rs
> +        /// User initiated a redeem. [CurrencyIdOf<T>, T::AccountId, BalanceOf<T>]
This comment seems outdated

2022-04-13 07:46 UTC, ebma commented on pallets/spacewalk/src/lib.rs
> +			let currency_id = T::StringCurrencyConversion::convert((asset_code.clone(), asset_issuer.clone()))
Indentation seems a bit off here

2022-04-13 10:22 UTC, gonzamontiel requested changes

2022-04-13 10:22 UTC, gonzamontiel commented on .gitignore
> -.vscode
Was this change intended?

2022-04-13 10:22 UTC, gonzamontiel commented on .vscode/launch.json
> +{
I thought the `.vscode` folder should be ignored, is there a reason we want this for all the contributors?

2022-04-13 12:57 UTC, ashneverdawn commented on pallets/spacewalk/src/lib.rs
> +        /// User initiated a redeem. [CurrencyIdOf<T>, T::AccountId, BalanceOf<T>]
fixed

2022-04-13 12:57 UTC, ashneverdawn commented on pallets/spacewalk/src/lib.rs
> +			let currency_id = T::StringCurrencyConversion::convert((asset_code.clone(), asset_issuer.clone()))
fixed

2022-04-13 12:58 UTC, ashneverdawn commented on .gitignore
> -.vscode
no, resolved

2022-04-20 10:45 UTC, gonzamontiel approved these changes

2022-04-20 10:45 UTC, merged