244 - Change handling of open requests
pendulum-chain/spacewalk pull request #245
Opened 2023-02-08 16:27 UTC by b-yap

2023-02-08 17:45 UTC, cr4pt0 approved these changes

2023-02-08 18:38 UTC, ebma requested changes
We should change it to store unsuccessful requests and retry them instead.

2023-02-08 19:01 UTC, cr4pt0 approved these changes

2023-02-09 16:40 UTC, ebma commented on clients/vault/src/execution.rs
> +		}
Should we add a line that prints some log if we exhausted all our retry counts and it still did not work? Or should we maybe in l. 280 mention that we are retrying and also mention the retry count?

2023-02-09 16:40 UTC, ebma commented on clients/vault/src/execution.rs
> +					break
Can we rewrite it with a match statement to make it more obvious that we break the while function on successful submit? It took me a second to figure out why we `continue` in one case and `break` afterwards. Maybe that makes it clearer.

2023-02-10 09:55 UTC, ebma approved these changes

2023-02-10 15:16 UTC, merged