398 client runner
pendulum-chain/spacewalk pull request #400
Opened 2023-09-14 17:13 UTC by gianfra-t

Addition of an implementation of the [runner client](https://github.com/interlay/interbtc-clients/tree/master/runner) taken from interlay clients.

In summary, the runner fetches periodically for the on-chain information about the vault client, both download URI and checksum. It will then proceed to download and execute it, also checking for new releases and handling them. 

The only difference on this implementation is:
- The runner client will now verify checksum of the vault client once it is downloaded for the first time, rejecting the download if it does not match.
- The runner will retry the download if it fails (for instance, if the checksum is incorrect)

2023-09-14 17:49 UTC, ebma requested changes

2023-09-14 17:49 UTC, ebma commented on runner/Cargo.toml
> +sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42" }
Let's keep this in sync with the other dependencies and use `polkadot-v0.9.40`

2023-09-14 17:49 UTC, ebma commented on clients/README.md
> +Once the local node is running, run this command from the clients directory:
Nice, can we change the command in line 92 to specify installation of a fixed subxt version? Something like `cargo install subxt-cli@0.31.0`

2023-09-14 17:49 UTC, ebma commented on runner/Cargo.toml
I would say we move the whole `runner` directory into the `clients` directory instead of placing it in root.

2023-09-14 17:49 UTC, ebma commented on runner/src/runner.rs
> +pub const PARACHAIN_MODULE: &str = "ClientInfo";
I assume this matters.
```suggestion
pub const PARACHAIN_MODULE: &str = "ClientsInfo";
```

2023-09-14 17:49 UTC, ebma commented on runner/src/runner.rs
> +pub const BLOCK_TIME: Duration = Duration::from_secs(6);
Should be 12 seconds actually (?)

2023-09-14 17:49 UTC, ebma commented on runner/src/runner.rs
> +/// Waiting interval used by the retry utilities: One minute
Comment does not match the actual value of `1_000` milliseconds.

2023-09-14 17:49 UTC, ebma commented on runner/src/runner.rs
> +	/// Example: https://github.com/interlay/interbtc-clients/releases/download/1.16.0/vault-parachain-metadata-interlay
Let's adjust the comment and replace the link with this one. 
`https://downloads.pendulumchain.tech/index.html`

2023-09-14 17:49 UTC, ebma commented on runner/src/runner.rs
> +	/// The child process (interbtc client) spawned by this runner
```suggestion
	/// The child process (Spacewalk client) spawned by this runner
```

2023-09-14 17:49 UTC, ebma commented on runner/src/runner.rs
> +		//Runner::do_download_binary(runner ,release.clone()).await?;
Can we remove this line?

2023-09-14 17:49 UTC, ebma commented on runner/src/runner.rs
> +		Ok("success")
If we don't care about the content of the Result, let's just go for a `Result<(), Error>` and remove the `"success"`

2023-09-14 17:49 UTC, ebma commented on runner/src/runner.rs
> +					// as the Bitcoin wallet for vaults).
```suggestion
					// as the Stellar wallet for vaults).
```

2023-09-14 17:49 UTC, ebma commented on runner/src/runner.rs
> +			assert_eq!(bin_name, "vault-parachain-metadata-kintsugi");
Can we change this to something spacewalk-related?

2023-09-14 17:49 UTC, ebma commented on runner/src/runner.rs
> +			"ws://localhost:9944",
I assume we actually have to change these arguments because some of them are not supported by our vault client.

2023-09-14 17:50 UTC, ebma reviewed
Looks good overall, I just left some comments about minor issues.

2023-09-14 18:05 UTC, gianfra-t commented on runner/src/runner.rs
> +pub const PARACHAIN_MODULE: &str = "ClientInfo";
It does!!

2023-09-14 18:45 UTC, gianfra-t commented
Thanks for finding [this](https://github.com/pendulum-chain/spacewalk/pull/400#discussion_r1326310708) @ebma! on that note, let me know if we should open a separate task to build an integration test for the runner.

2023-09-15 16:19 UTC, gianfra-t commented
The CI seems to be failing when [connecting to stellar](https://github.com/pendulum-chain/spacewalk/blob/31df1832483199b978ae07f6ed4e018a11ff4dba/clients/stellar-relay-lib/src/connection/services.rs#L21), perhaps we retry later?

2023-09-28 11:59 UTC, ebma commented
> On that note, let me know if we should open a separate task to build an integration test for the runner.

How would you suggest we approach this kind of test?

2023-09-28 12:39 UTC, ebma approved these changes
The code looks good overall. 

How sure are we that this works as expected though @gianfra-t? You said you tested it locally once and it worked with downloading the binary from a target location and replacing the current vault executable, correct?

2023-09-28 13:54 UTC, gianfra-t commented
> The code looks good overall.
> 
> How sure are we that this works as expected though @gianfra-t? You said you tested it locally once and it worked with downloading the binary from a target location and replacing the current vault executable, correct?

Yes. I tested locally with a release of the client and also tested updating it on a local chain. It detected the changes and downloaded/started the new one.

2023-09-28 17:51 UTC, ebma commented
I also tested it and can confirm that the runner manages to read the URL stored in the clients-info pallet and downloads the release from there. However, the checksum did not match. 
@gianfra-t During testing, how did you calculate the checksum for the `clientsInfo::setCurrentClientReleases()` extrinsic? Using the 'hash a file' option provided by polkadot.js does not seem to work, or at least the result of that hashing process is not the same as the result of the runner hashing the downloaded binary.

To make it work regardless, I just used the hash that the runner calculates and put that on chain. Afterward, downloading etc. worked. But this is not an ideal solution of course.

2023-09-28 17:57 UTC, gianfra-t commented
I actually had the same problem, the polkadot.js hash did not work. I thought it was a problem with it so I used [this tool](https://emn178.github.io/online-tools/sha256_checksum.html). Do you think it is a different hashing algorithm/implementation? 
I it presents a problem I guess I could try a different hashing library on the runner that matches the one created by polkadot.js

2023-09-29 08:34 UTC, ebma commented
Yes, let's try to use the same hashing algorithm for convenience. I tried to find what polkadot.js uses and I think it is blake2. The UI calls [this](https://github.com/polkadot-js/apps/blob/2ea78003faed0e63eb9c3dec1694508f45624e9d/packages/react-params/src/Param/Hash256.tsx#L22-L23) function and according to [this](https://github.com/polkadot-js/api/blob/0dcf349831a9b62acc4f00612e0c63b2c8b42de4/packages/types/src/create/registry.spec.ts#L163-L164) test it uses blake2 by default but can be overridden with a custom definition [here](https://github.com/polkadot-js/api/blob/0dcf349831a9b62acc4f00612e0c63b2c8b42de4/packages/api/src/base/Init.ts#L92). I think we don't specify a custom hasher so let's try hashing with blake2 in the vault client and see if the checksum then matches the one generated by polkadot.js upon file upload.

2023-09-29 12:22 UTC, gianfra-t commented
I would say It really boils down to our deployment workflow we want.
If we plan to have a release of the client that is automated then I would say stick with this hashing algorithm and do something similar to interlay.

2023-09-29 14:48 UTC, ebma commented
Alright. Let's stick to sha256 and not rely on the hash shown in polkadot.js. It's just a UI and we can use other means, like e.g. the tool you linked to. 
So in theory this PR is ready for merge now but I'm hesitant to merge it just yet because the CI is failing.

2023-09-29 15:12 UTC, gianfra-t commented
It's the issue related to stellar update, so let's wait for that to be solved and we can merge those changes.

2023-10-13 12:46 UTC, merged